#!/bin/bash -eu

export SANITIZER_FLAGS=$SANITIZER_FLAGS_address
export CFLAGS="$CFLAGS $SANITIZER_FLAGS $COVERAGE_FLAGS"
export CXXFLAGS="$CFLAGS $CXXFLAGS_EXTRA"
export CXXFLAGS="$CXXFLAGS -I $SRC/cryptofuzz/fuzzing-headers/include"
export CXXFLAGS="$CXXFLAGS -DCRYPTOFUZZ_EVERCRYPT -DCRYPTOFUZZ_LIBSODIUM"
